In [2]:
import tensorflow as tf
from __future__ import print_function

In [7]:
#creating constants
a=tf.constant(3)
b=tf.constant(9)
c=a+b

In [10]:
print(c)

tf.Tensor(12, shape=(), dtype=int32)


In [11]:
print(a*b)

tf.Tensor(27, shape=(), dtype=int32)


In [13]:
print(b/a)

tf.Tensor(3.0, shape=(), dtype=float64)


In [14]:
#built-in add
c=tf.add(a,b)
print(c)

tf.Tensor(12, shape=(), dtype=int32)


In [8]:
#matrix multiplication-- 4*3+8*2
x=tf.constant([[3,8]])
y=tf.constant([[4],[2]])
z=tf.matmul(x,y)
print(z)

tf.Tensor([[28]], shape=(1, 1), dtype=int32)


In [33]:
#matrix addition
x=tf.constant([1,2,3])
y=tf.constant([7,8,2])
print(tf.add(x,y))

tf.Tensor([ 8 10  5], shape=(3,), dtype=int32)


In [34]:
print(tf.subtract(x,y))

tf.Tensor([-6 -6  1], shape=(3,), dtype=int32)


In [35]:
print(tf.divide(x,y))

tf.Tensor([0.14285714 0.25       1.5       ], shape=(3,), dtype=float64)


In [36]:
print(tf.multiply(x,y))

tf.Tensor([ 7 16  6], shape=(3,), dtype=int32)


In [40]:
#1*7+2*8...
print(tf.tensordot(x,y,axes=1))

tf.Tensor(29, shape=(), dtype=int32)


In [6]:
#1matrix with 2 rows 1 col
x=tf.constant([[4.],[2.]])
x

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[4.],
       [2.]], dtype=float32)>

In [25]:
#2matrix with 1 row 2 col
x=tf.constant([[3.,8.]])
print(x)

tf.Tensor([[3. 8.]], shape=(1, 2), dtype=float32)


In [26]:
#3matrix
a=tf.constant([[1,2,3],[4,5,6]])
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [17]:
#creating a matrix of ones with 3 rows 2 col
x=tf.ones([3,2])
x

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [18]:
#cretaing matrix of zeros with 4 rows and 2 col
x=tf.zeros([4,2])
x

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [22]:
#to update elements of matrix convert the matrix to variable and use the assign method
x=tf.Variable(x)
x[2,1].assign(3)

<tf.Variable 'UnreadVariable' shape=(4, 2) dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 3.],
       [0., 0.]], dtype=float32)>

In [30]:
#creating identity matrix
x=tf.eye(3)
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [31]:
x=tf.random.normal([3,2],mean=1,stddev=1)
x

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.17243701, 1.4622041 ],
       [2.3043773 , 1.667284  ],
       [0.5736644 , 0.84221435]], dtype=float32)>

In [32]:
x=tf.random.uniform([3,2],minval=1,maxval=5)
x

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[4.6177607, 2.7895656],
       [4.446918 , 1.5235686],
       [3.9732876, 4.71663  ]], dtype=float32)>

In [12]:
#indexing
x=tf.constant([[6,2],
                [4,6],
                [7,8]])
x[0,:]

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[6, 2],
       [4, 6],
       [7, 8]])>

In [7]:
#row 0 and all col
x[0,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 2])>

In [20]:
#row from 0 to 3 and col 0
x[0:3,0:1]

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[6],
       [4],
       [7]])>

In [21]:
#reshape
x=tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [23]:
x_reshaped=tf.reshape(x,[3,3])
x_reshaped

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

In [24]:
#transpose
x=tf.transpose(x_reshaped, perm=[1,0])
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])>